#!/bin/sh

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
    set -x
fi

# The sed expression here replaces all backslashes by forward slashes.
# This helps our Windows users, while not bothering our Unix users.
export GITFLOW_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

usage() {
    echo "usage: rmb <subcommand> [options]"
    echo
    echo "Available subcommands are:"
    echo "  clone         just the same as git clone."
    echo "  branch/br     just the same as git branch."
    echo "  push          sync local branch to remote branch, for integration testing."
    echo "  release/rl    merge local branch to remote master, for production."
}

main() {
    if [ $# -lt 1 ]; then
        usage
        exit 1
    fi
}
